USE EMPRESA

SELECT * FROM CNH
SELECT * FROM EMAIL
SELECT * FROM TELEFONE
SELECT * FROM PESSOA

SELECT nomePessoa, numeroTelefone, enderecoEmail, descricao
FROM PESSOA
INNER JOIN TELEFONE
ON PESSOA.idPessoa = TELEFONE.idPessoa
INNER JOIN EMAIL
ON PESSOA.idPessoa = EMAIL.idPessoa
INNER JOIN CNH
ON PESSOA.idPessoa = CNH.idPessoa
ORDER BY nomePessoa DESC