USE LOCADORA 
GO

SELECT * FROM EMPRESA;
GO

SELECT * FROM CLIENTE; 
GO

SELECT * FROM MARCA; 
GO

SELECT * FROM MODELO;
GO

SELECT * FROM VICULO;
GO

SELECT * FROM ALUGUEL;
GO

SELECT nomeCliente, DataDevolver, DataAluguel, nomeModelo 
FROM ALUGUEL
INNER JOIN CLIENTE
ON CLIENTE.IdCliente = ALUGUEL.IdAlguel
INNER JOIN CLIENTE
ON CLIENTE.IdCliente = MODELO.IdModelo
WHERE CLIENTE.nomeCliente = 'David'  