CREATE DATABASE PCLINICS
GO

USE PCLINICS
GO

CREATE TABLE CLINICA(
IdClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
NomeClinica VARCHAR(20) NOT NULL, 
enderecoCLinica VARCHAR(20) NOT NULL
);
GO 

CREATE TABLE DONO(
IdDono SMALLINT PRIMARY KEY IDENTITY(1,1),
NomeDono VARCHAR(20) NOT NULL
);
GO
CREATE TABLE RACA(
IdRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
NomeDono VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TIPO(
IdTipo SMALLINT PRIMARY KEY IDENTITY(1,1),
IdRaca SMALLINT FOREIGN KEY REFERENCES RACA(IdRaca),
NomeTipo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE PET(
IdPet SMALLINT PRIMARY KEY IDENTITY(1,1),
IdDono SMALLINT FOREIGN KEY REFERENCES DONO(IdDono),
IdTipo SMALLINT FOREIGN KEY REFERENCES TIPO(IdTipo),
nomePet VARCHAR(20) NOT NULL,
dataNiver VARCHAR(8) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
IdVeterinario SMALLINT PRIMARY KEY IDENTITY(1,1),
IdClinica SMALLINT FOREIGN KEY REFERENCES CLINICA(IdClinica),
NomeVet VARCHAR(25) NOT NULL
CRMV VARCHAR(5) NOT NULL 
);
GO