CREATE DATABASE CATALOGO;
GO

CREATE TABLE GENERO(
IdGenero TINYINT PRIMARY KEY INDETITY(1,1)
nomeGenero VARCHAR(20)
);
GO

CREATE TABLE FILMES(
IdFilme SMALLINT PRIMARY KEY IDENTITY(1,1),
IdGenero TINYINT FOREIGN KEY REFERENCES GENERO(IdGenero),
itutloFilme VARCAHR (80) NOT NULL
);
GO